# Generated by Django 5.0.8 on 2026-05-28 23:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=64, verbose_name='Сущность')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('date', 'Дата'), ('boolean', 'Да/нет')], default='text', max_length=16, verbose_name='Тип')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательное')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Пользовательское поле',
                'verbose_name_plural': 'Пользовательские поля',
                'ordering': ['entity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DealStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('color', models.CharField(default='#64748b', max_length=20, verbose_name='Цвет')),
                ('is_won', models.BooleanField(default=False, verbose_name='Успешный финал')),
                ('is_lost', models.BooleanField(default=False, verbose_name='Отказ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Этап сделки',
                'verbose_name_plural': 'Этапы сделок',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationPlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('nova_poshta', 'Новая Почта'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('telephony', 'Телефония')], max_length=32, unique=True, verbose_name='Провайдер')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Включено')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Конфигурация')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Интеграция',
                'verbose_name_plural': 'Интеграции',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('sku', models.CharField(max_length=80, unique=True, verbose_name='Артикул')),
                ('category', models.CharField(blank=True, max_length=140, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Цена продажи')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Себестоимость')),
                ('stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Остаток')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('draft', 'Черновик'), ('archived', 'Архив')], default='active', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создание'), ('updated', 'Изменение'), ('deleted', 'Удаление'), ('status_changed', 'Изменение статуса')], max_length=32, verbose_name='Действие')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='ID объекта')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Объект')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип объекта')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История действия',
                'verbose_name_plural': 'История действий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя / компания')),
                ('client_type', models.CharField(choices=[('person', 'Физическое лицо'), ('company', 'Компания')], default='person', max_length=16, verbose_name='Тип')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('active', 'Активный'), ('vip', 'VIP'), ('archived', 'Архив')], default='new', max_length=16, verbose_name='Статус')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Основной телефон')),
                ('extra_phones', models.JSONField(blank=True, default=list, verbose_name='Дополнительные телефоны')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Основной email')),
                ('extra_emails', models.JSONField(blank=True, default=list, verbose_name='Дополнительные email')),
                ('telegram', models.CharField(blank=True, max_length=120, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=255, verbose_name='Instagram')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Теги')),
                ('notes', models.TextField(blank=True, verbose_name='Внутренние заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_clients', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Имя')),
                ('position', models.CharField(blank=True, max_length=120, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram', models.CharField(blank=True, max_length=120, verbose_name='Telegram')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной контакт')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='Источник')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=16, verbose_name='Приоритет')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма')),
                ('probability', models.PositiveSmallIntegerField(default=20, verbose_name='Вероятность, %')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='Ожидаемое закрытие')),
                ('description', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.client', verbose_name='Клиент')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_deals', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.dealstage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['stage__order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('kind', models.CharField(choices=[('info', 'Информация'), ('task', 'Задача'), ('deal', 'Сделка'), ('order', 'Заказ'), ('integration', 'Интеграция'), ('warning', 'Важно')], default='info', max_length=24, verbose_name='Тип')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Номер')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачен'), ('partial', 'Частично'), ('paid', 'Оплачен')], default='unpaid', max_length=16, verbose_name='Оплата')),
                ('delivery_status', models.CharField(choices=[('new', 'Не отправлен'), ('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('returned', 'Возврат')], default='new', max_length=16, verbose_name='Доставка')),
                ('work_status', models.CharField(choices=[('processing', 'В обработке'), ('in_work', 'В работе'), ('ready', 'Готов'), ('closed', 'Закрыт')], default='processing', max_length=16, verbose_name='Работа')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Скидка')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Итого')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.client', verbose_name='Клиент')),
                ('deal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='crm.deal', verbose_name='Сделка')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_orders', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Скидка')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('director', 'Руководитель'), ('manager', 'Менеджер'), ('production', 'Склад / производство')], default='manager', max_length=32, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('position', models.CharField(blank=True, max_length=120, verbose_name='Должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('done', 'Выполнена'), ('canceled', 'Отменена')], default='active', max_length=16, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=16, verbose_name='Приоритет')),
                ('overdue_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Уведомление о просрочке')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Поставил')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.deal', verbose_name='Сделка')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['status', 'deadline', '-created_at'],
            },
        ),
    ]
