# Generated by Django 5.0.8 on 2026-05-28 23:28

from django.db import migrations


def seed_defaults(apps, schema_editor):
    DealStage = apps.get_model("crm", "DealStage")
    IntegrationPlaceholder = apps.get_model("crm", "IntegrationPlaceholder")
    CustomField = apps.get_model("crm", "CustomField")

    stages = [
        ("Новая заявка", 10, "#3b82f6", False, False),
        ("В работе", 20, "#8b5cf6", False, False),
        ("КП / расчет", 30, "#f97316", False, False),
        ("Ожидание ответа", 40, "#eab308", False, False),
        ("Подтверждено", 50, "#14b8a6", False, False),
        ("Передано в работу", 60, "#06b6d4", False, False),
        ("Завершено", 70, "#22c55e", True, False),
        ("Отказ", 80, "#ef4444", False, True),
    ]
    for name, order, color, is_won, is_lost in stages:
        DealStage.objects.get_or_create(
            name=name,
            defaults={"order": order, "color": color, "is_won": is_won, "is_lost": is_lost},
        )

    for provider in ["nova_poshta", "telegram", "instagram", "telephony"]:
        IntegrationPlaceholder.objects.get_or_create(provider=provider, defaults={"is_enabled": False, "config": {}})

    for entity, name, field_type in [
        ("client", "Источник клиента", "text"),
        ("deal", "Причина отказа", "text"),
        ("order", "Дата плановой отгрузки", "date"),
    ]:
        CustomField.objects.get_or_create(entity=entity, name=name, defaults={"field_type": field_type})


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_defaults, migrations.RunPython.noop),
    ]
