# Generated by Django 5.0.8 on 2026-05-29 10:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_seed_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название')),
                ('template_type', models.CharField(choices=[('offer', 'Коммерческое предложение'), ('invoice', 'Счет'), ('contract', 'Договор')], default='offer', max_length=32, verbose_name='Тип')),
                ('body', models.TextField(verbose_name='Шаблон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BotLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('telegram', 'Telegram bot'), ('instagram', 'Instagram'), ('website', 'Сайт')], default='telegram', max_length=32, verbose_name='Источник')),
                ('name', models.CharField(max_length=180, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.client', verbose_name='Созданный клиент')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.deal', verbose_name='Созданная сделка')),
            ],
            options={
                'verbose_name': 'Заявка чат-бота',
                'verbose_name_plural': 'Заявки чат-ботов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('incoming', 'Входящий'), ('outgoing', 'Исходящий')], default='incoming', max_length=16, verbose_name='Направление')),
                ('status', models.CharField(choices=[('answered', 'Принят'), ('missed', 'Пропущен')], default='answered', max_length=16, verbose_name='Статус')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('recording', models.FileField(blank=True, upload_to='calls/%Y/%m/', verbose_name='Запись звонка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('task_created', models.BooleanField(default=False, verbose_name='Задача создана')),
                ('called_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата звонка')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='crm.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
                'ordering': ['-called_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='clients/%Y/%m/', verbose_name='Файл')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='Название')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crm.client', verbose_name='Клиент')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл клиента',
                'verbose_name_plural': 'Файлы клиентов',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Скидка')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.deal', verbose_name='Сделка')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар сделки',
                'verbose_name_plural': 'Товары сделки',
            },
        ),
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('telephony', 'Телефония'), ('manual', 'Вручную')], max_length=32, verbose_name='Канал')),
                ('sender_name', models.CharField(blank=True, max_length=160, verbose_name='Отправитель')),
                ('sender_handle', models.CharField(blank=True, max_length=160, verbose_name='Контакт')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('linked', 'Привязано'), ('processed', 'Обработано')], default='new', max_length=24, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='crm.client', verbose_name='Клиент')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='crm.deal', verbose_name='Сделка')),
            ],
            options={
                'verbose_name': 'Сообщение inbox',
                'verbose_name_plural': 'Сообщения inbox',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/%Y/%m/', verbose_name='Файл')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='Название')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crm.order', verbose_name='Заказ')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл заказа',
                'verbose_name_plural': 'Файлы заказов',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('nova_poshta', 'Новая Почта')], default='nova_poshta', max_length=32, verbose_name='Служба')),
                ('tracking_number', models.CharField(blank=True, max_length=80, verbose_name='ТТН')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('created', 'ТТН создана'), ('in_transit', 'В пути'), ('delivered', 'Доставлено'), ('returned', 'Возврат')], default='draft', max_length=24, verbose_name='Статус')),
                ('recipient_city', models.CharField(blank=True, max_length=160, verbose_name='Город')),
                ('recipient_warehouse', models.CharField(blank=True, max_length=255, verbose_name='Отделение')),
                ('api_payload', models.JSONField(blank=True, default=dict, verbose_name='Данные API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='crm.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Отправление',
                'verbose_name_plural': 'Отправления',
                'ordering': ['-updated_at'],
            },
        ),
    ]
