# Generated by Django 5.0.8 on 2026-05-30 11:20

from django.db import migrations, models


def seed_stage_split(apps, schema_editor):
    DealStage = apps.get_model("crm", "DealStage")
    kp_stage, _ = DealStage.objects.get_or_create(name="КП", defaults={"order": 30, "color": "#f97316", "is_active": True})
    DealStage.objects.get_or_create(name="Расчет", defaults={"order": 35, "color": "#fb923c", "is_active": True})
    DealStage.objects.get_or_create(name="Оплата", defaults={"order": 45, "color": "#eab308", "is_active": True})
    old_stage = DealStage.objects.filter(name="КП / расчет").first()
    if old_stage:
        old_stage.deals.update(stage=kp_stage)
        old_stage.is_active = False
        old_stage.save(update_fields=["is_active"])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_documenttemplate_botlead_calllog_clientfile_dealitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_contact_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='Имя обратившегося'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='source',
            field=models.CharField(blank=True, choices=[('site', 'Сайт'), ('website', 'Сайт'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('phone', 'Телефон'), ('referral', 'Рекомендация'), ('manual', 'Ручной ввод')], max_length=32, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.RunPython(seed_stage_split, migrations.RunPython.noop),
    ]
