# Generated by Django 5.0.8 on 2026-05-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_client_company_name_client_primary_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя / компания'),
        ),
    ]
